//Generated by ChatGPT-4o

import {IUserData} from "../canvasDataDefs";

export const mockUserData: IUserData = {
    id: 1,
    name: 'John Doe',
    sortable_name: 'Doe, John',
    last_name: 'Doe',
    first_name: 'John',
    short_name: 'J. Doe',
    email: 'john.doe@example.com',
    bio: 'This is a bio for John Doe.',
};